domain_path: /home/user8/workspace_semicon/verilog/soc2024_2/platform_led_sw/export/platform_led_sw/sw/standalone_microblaze_riscv_0
app_src_dir: /home/user8/Tools/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
